#!/usr/bin/env ruby
# frozen_string_literal: true

# Copyright 2015-2017 Hyeon Kim
#
# Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
# http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
# <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
# option. This file may not be copied, modified, or distributed
# except according to those terms.

require 'cinch'
require 'nokogiri'
require 'open-uri'
require 'date'
require 'daumdic'

bot = Cinch::Bot.new do
  configure do |c|
    c.nick = '김젼봇'
    c.realname = 'love'
    c.user = 'slavery'

    c.server = 'irc.ozinger.org'
    c.port = 6697
    c.ssl.use = true

    c.channels = ['#test']
    c.max_reconnect_delay = 60
  end

  on :message, /^[dD](?:ic)? (.+)$/ do |m, query|
    result = Daumdic.search(query)
    result = 'ㅇㅅㅇ)a' if result.nil?

    m.reply result
  end

  on :message, 'ㅇㅅㅇ)b' do |m|
    m.reply 'd(ㅇㅅㅇ'
  end

  on :message, '>ㅅㅇ' do |m|
    m.reply 'ㅇㅅ<'
  end
end

bot.loggers.level = :warn
bot.start
