#!/usr/bin/env ruby
# frozen_string_literal: true

# Copyright 2015-2017 Hyeon Kim
#
# Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
# http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
# <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
# option. This file may not be copied, modified, or distributed
# except according to those terms.

require 'yaml'
require 'json'
require 'cinch'
require 'daumdic'

def load_config_from_file(default, filename)
  begin
    data = YAML.load_file(filename)
  rescue Errno::ENOENT, Psych::SyntaxError
    return default
  end
  return default if data.class != Hash

  server    = data['server'   ]
  port      = data['port'     ]
  log_level = data['log_level']&.to_sym

  config = {}
  config[:server   ] = server    || default[:server   ]
  config[:port     ] = port      || default[:port     ]
  config[:log_level] = log_level || default[:log_level]
  return config
end

def load_config_from_env(default)
  server    = ENV['HYEONBOT_SERVER'   ]
  port      = ENV['HYEONBOT_PORT'     ]&.to_i
  log_level = ENV['HYEONBOT_LOG_LEVEL']&.to_sym

  config = {}
  config[:server   ] = server    || default[:server   ]
  config[:port     ] = port      || default[:port     ]
  config[:log_level] = log_level || default[:log_level]

  return config
end

#
# Load configs
#
config = {
  # Default configs
  server:     'irc.ozinger.org',
  port:       6697,
  log_level:  :debug,
}

config = load_config_from_file(config, '/etc/hyeonbot/config.yaml')
config = load_config_from_file(config, 'config.yaml')
config = load_config_from_env(config)

#
# Connect to the network
#
bot = Cinch::Bot.new do |b|
  configure do |c|
    c.nick = '김젼봇'
    c.realname = 'IRC Robot. See https://github.com/simnalamburt/hyeonbot for the reference.'
    c.user = 'hyeonbot'

    c.server = config[:server]
    c.port = config[:port]
    c.ssl.use = true

    c.max_reconnect_delay = 60
  end

  # Daum dictionary
  on :message, /^[dD](?:ic)? (.+)$/ do |m, query|
    result = Daumdic.one_liner(query)
    result = 'ㅇㅅㅇ)a' if result.nil?

    m.reply result
  end

  # Health check
  on :message, 'ㅇㅅㅇ)b' do |m|
    m.reply 'd(ㅇㅅㅇ'
  end
  on :message, '>ㅅㅇ' do |m|
    m.reply 'ㅇㅅ<'
  end

  # 올바른 언어생활
  on :message, /우리나라/ do |m|
    m.reply '우리나라 → 한국'
  end
  on :message, /한글화/ do |m|
    m.reply '한글화 → 한국어 번역 ' + Cinch::Formatting.format(:grey, 'https://t.co/ztyockmyrj 참고')
  end
  on :message, /쉐어/ do |m|
    m.reply '쉐어 → 셰어 ' + Cinch::Formatting.format(:grey, '쉘 → 셸, 솨프 → 샤프')
  end
  on :message, /됬/ do |m|
    m.reply '됬 → 됐'
  end

  # React on invitation
  on :invite do |m|
    b.join m.channel
  end
end

# Handle ^C gracefully
trap 'SIGINT' do
  print "\n\nBye!\n\n"
  exit
end

bot.loggers.level = config[:log_level]
bot.start
