on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo test
      - run: cargo clippy --workspace --all-targets --all-features -- -D warnings
      - run: cargo fmt --all --check
